### ISSUE TITLE
Creating CW alarms across multiple regions

### ISSUE THREAD

**Issue by james-jory** [aws-samples/amazon-personalize-monitor#5]
When deploying with either of the alarm parameters set to "Yes" _and_ when multiple regions are specified, the alarms fail to create because there is only one SNS topic created at deployment in the deployment region. The workaround is to only monitor resources in the same region where this solution is deployed (i.e. single region) and then deploy multiple instances of this app or do not enable alarms to be created.

**Comment by james-jory** [comment]
More details on a workaround for this issue until it is permanently fixed. Note that this workaround is **only necessary if you want to monitor across multiple regions _AND_ use alarms in those regions**. If you just want to monitor resources across multiple regions, this workaround is not necessary.

- Install/deploy this solution separately into every region where you want Personalize resources monitored where each deployment only monitors the resources in the region where it is deployed.
  - If you're deploying using [SAR](https://aws.amazon.com/serverless/serverlessrepo/), select the target region in the console user interface before installing the application.
  - If you're deploying using SAM, specify the target region on the command line for `sam deploy` (e.g., `sam deploy --region us-east-1`).
  - When deploying, you are prompted for the region(s) that you want to monitor as a template parameter. Enter **only** the target region where you are deploying the solution.
  - Repeat the process above to deploy the solution in all the desired regions.
- At this point, the Personalize Monitor deployments in each region will be setup to monitor and alarm on resources in each region. However, the CloudWatch dashboard will not reflect all resources across all regions covered by the separate deployments. Let's fix that.
  - To get the Personalize Monitor CloudWatch dashboard to show monitored resources across all regions, you need to change the `Region` environment variable for the DashboardManagementFunction Lambda function to list all regions as a comma delimited list. **This must be done for each DashboardManagementFunction in each deployed region.** For example, if I deployed the solution into `us-east-1`, `us-east-2`, and `us-west-2`, the `Regions` environment variable should be set to `us-east-1,us-east-2,us-west-2`. You can find the function either in the SAR resources (if you deployed using SAR), in CloudFormation for the solution's stack (under Resources), or in the Lambda console. **Only make this change for the dashboard management function in each deployed region**.
- Manually run the DashboardManagementFunction Lambda function by creating a dummy test event (the event doesn't matter) and test the function. This will rebuild the dashboard based on resources in all regions listed in `Regions`. You only need to manually run the function once in one of the regions.

**Limitation**: there is one limitation with this workaround and that is the "Campaigns Monitored" count in the dashboard may not be accurate. Note this is just the count; all configured campaigns are still being monitored. Just the count may be off.

**Comment by programmeranand** [comment]
> More details on a workaround for this issue until it is permanently fixed. Note that this workaround is **only necessary if you want to monitor across multiple regions _AND_ use alarms in those regions**. If you just want to monitor resources across multiple regions, this workaround is not necessary.
> 
> * Install/deploy this solution separately into every region where you want Personalize resources monitored where each deployment only monitors the resources in the region where it is deployed.
>   
>   * If you're deploying using [SAR](https://aws.amazon.com/serverless/serverlessrepo/), select the target region in the console user interface before installing the application.
>   * If you're deploying using SAM, specify the target region on the command line for `sam deploy` (e.g., `sam deploy --region us-east-1`).
>   * When deploying, you are prompted for the region(s) that you want to monitor as a template parameter. Enter **only** the target region where you are deploying the solution.
>   * Repeat the process above to deploy the solution in all the desired regions.
> * At this point, the Personalize Monitor deployments in each region will be setup to monitor and alarm on resources in each region. However, the CloudWatch dashboard will not reflect all resources across all regions covered by the separate deployments. Let's fix that.
>   
>   * To get the Personalize Monitor CloudWatch dashboard to show monitored resources across all regions, you need to change the `Region` environment variable for the DashboardManagementFunction Lambda function to list all regions as a comma delimited list. **This must be done for each DashboardManagementFunction in each deployed region.** For example, if I deployed the solution into `us-east-1`, `us-east-2`, and `us-west-2`, the `Regions` environment variable should be set to `us-east-1,us-east-2,us-west-2`. You can find the function either in the SAR resources (if you deployed using SAR), in CloudFormation for the solution's stack (under Resources), or in the Lambda console. **Only make this change for the dashboard management function in each deployed region**.
> * Manually run the DashboardManagementFunction Lambda function by creating a dummy test event (the event doesn't matter) and test the function. This will rebuild the dashboard based on resources in all regions listed in `Regions`. You only need to manually run the function once in one of the regions.
> 
> **Limitation**: there is one limitation with this workaround and that is the "Campaigns Monitored" count in the dashboard may not be accurate. Note this is just the count; all configured campaigns are still being monitored. Just the count may be off.

@james-jory Using the workaround the Personalize Monitor and Alarms gets Deployed successfully but the workaround for Dashboard Fix using manually changing `DashboardManagementFunction ` is not working. 
Currently, in my case, the following happened
1. When I manually ran the `DashboardManagementFunction` the Dashboard got build successfully and pulled data from all regions
2. After a few hours the Dashboard automatically changed to show Information for only 1 specific region

**Comment by james-jory** [comment]
Hi @programmeranand. Did you update the `Regions` environment variable value for the `DashboardManagementFunction` in each region where it was deployed? This is important since that function will be executed in each region and needs to be aware of the complete list of regions.

**Comment by programmeranand** [comment]
> 

Hi @james-jory yes, I have updated “Regions” environment variable for the dashboard management function in all regions deployed and did the manual trigger of the DashboardManagementFunction as explained in your comment. Post this the Dashboard gets populated correctly once DashboardManagementFunction is run with Test Event and shows all regions Campaigns. but after a few hours, the Monitoring Dashboard changes and shows the Campaign of only 1 region.

**Comment by james-jory** [comment]
Odd. I am not seeing that behavior in my multi-region test deployment, @programmeranand.

**Comment by programmeranand** [comment]
> Odd. I am not seeing that behavior in my multi-region test deployment, @programmeranand.

@james-jory I tried digging deeper and found that for one of the regions the `DashboardManagementFunction` is correctly configured and `Regions` environment variable value has all the regions and on triggering the test event [as mentioned in workaround [here](https://github.com/aws-samples/amazon-personalize-monitor/issues/5#issuecomment-1483567341) ] it rebuilds the dashboard with all campaigns of all regions configured correctly, 

The issue seems that on scheduled trigger of this `DashboardManagementFunction` which happens from `PersonalizeMonitor` Lambda function the logs show only building the dashboard for only 1 region and ignores other regions thereby the Personalize Dashboard gets overridden with only 1 regions Campaigns automatically on next scheduled trigger of `DashboardManagementFunction`

For now I am using the workaround to manually use the test-event which is used to trigger the `DashboardManagementFunction` which successfully rebuilds the Dashboard Momentarily for an hour until the override occurs from the scheduled run as explained above
Let me know if you are able to reproduce this until we have a permanent fix

**Comment by james-jory** [comment]
The `DashboardManagementFunction` always checks the event and then environment variables to determine what campaign ARNs and regions to consider when rebuilding the dashboard. This is the case whether it's called manually, on a schedule, or as a result of an event fired from the `PersonalizeMonitorFunction`. Another requirement for the workaround to work as expected is that the `CampaignARNs` environment variable must be set to `all` (code [here](https://github.com/aws-samples/amazon-personalize-monitor/blob/master/src/layer/common.py#L125-L130)). Otherwise, there is no reason to look at the `Regions` variable. So double check that all `DashboardManagementFunction`'s across all deployments have `CampaignARNs` set to `all` and `Regions` set to a comma delimited list of your deployed regions.

**Comment by james-jory** [comment]
If you have this project deployed/installed from before this fix, be sure to fully uninstall/delete the project from **all** regions where it is installed and then reinstall the latest version. You only need to install the latest version once in one region to monitor and alert across multiple regions in the same account. In other words, the workaround noted above is no longer needed. Instead, either specify the regions that you want monitored in the "Regions" deployment parameter and "all" for "CampaignARNs" and/or "RecommenderARNs" or specify campaign and recommender ARNs from multiple regions in "CampaignARNs" and "RecommenderARNs", respectively. Since CloudWatch metric data is not deleted when the project is uninstalled, historical metric data will be present when the project is reinstalled.
